### ISSUE TITLE
Customize PFLogInView

### ISSUE THREAD

**Issue by marioGusmao** [ParsePlatform/ParseUI-iOS#25] opened 2015-01-07 18:28 UTC
Hi, i have problem customising PFLogInView

The passwordField and the usernameField if I remove the background they stay with a border around, how do i remove the border?
I didn´t get to the signup control yet but I imagine it has the same problem.

The problem is the PFTextField separatorStyle is internal and can't be set in the PFLogInView

The same issue is reported here: http://stackoverflow.com/questions/27648499/parse-com-pfloginview-uitextfield-display-issue-cant-remove-border

![ios simulator screen shot 07 jan 2015 18 21 16](https://cloud.githubusercontent.com/assets/1401552/5650852/05c68cf4-969a-11e4-86d1-016542690034.png)

**Comment by nlutsenko-fb** [comment] 2015-01-12 14:52
Duplicate of #9

**Closed by nlutsenko-fb** 2015-01-12 14:52 UTC
Labels: duplicate
