### ISSUE TITLE
PFLogInViewControllerDelegate not firing in demo project

### ISSUE THREAD

**Issue by estock** [ParsePlatform/ParseUI-iOS#203] opened 2015-11-19 16:15 UTC
I downloaded the sample project, and I'm attempting to run on my phone. When I run the demo project and login with Facebook, none of the delegate methods are firing ... 

```
#pragma mark -
#pragma mark PFLogInViewControllerDelegate

- (void)logInViewController:(PFLogInViewController *)logInController didLogInUser:(PFUser *)user {
    NSLog(@"User: %@", user);
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (void)logInViewControllerDidCancelLogIn:(PFLogInViewController *)logInController {
    // Do nothing, as the view controller dismisses itself
    NSLog(@"Login Canceled");
}

#pragma mark -
#pragma mark PFSignUpViewControllerDelegate

- (void)signUpViewController:(PFSignUpViewController *)signUpController didSignUpUser:(PFUser *)user {
    NSLog(@"Did Sign Up User: %@", user);
    [self dismissViewControllerAnimated:YES completion:nil];

}

- (void)signUpViewControllerDidCancelSignUp:(PFSignUpViewController *)signUpController {
    NSLog(@"Did Cancel Sign Up");
    // Do nothing, as the view controller dismisses itself
}
```

None of those are are printed when I login with facebook or twitter

**Comment by estock** [comment] 2015-11-19 16:21
just a correction, it appears that the twitter callback fires the delegate method, but not the facebook login

**Comment by estock** [comment] 2015-11-19 20:49
One more correction, It seems to work on the devices, but not on the simulator

**Comment by nlutsenko** [comment] 2015-11-19 20:50
@estock thanks for the report!
Which version of iOS is your simulator running?
Going to retest this in a minute and am curious...

**Comment by nlutsenko** [comment] 2015-11-19 22:03
@estock Turns out this is actually an FBSDK issue.
I am going to fix it here as well, so we double-guard it, but ultimately it's going to be fixed in the FBSDK repo (already submitted a fix internally).

The issue is due to the fact that by default `PFLogInViewController` doesn't ask for any permissions to FB, then if you already are authenticated with Facebook - FBSDK will report the authentication as cancelled unless you ask for new permissions. As a fix when you are using it - simply set `facebookPermissions` property on `PFLogInViewController` to say `@[ @"public_profile" ]`

**Closed** 2015-11-19 23:35 UTC
Labels: enhancement
