### ISSUE TITLE
[[PFTwitterUtils twitter] signRequest:request] does not seem to work anymore

### ISSUE THREAD

**Issue by tzapu** [ParsePlatform/ParseUI-iOS#139] opened 2015-08-27 05:46 UTC
Hi,
Since the move to ParseTwitterUtils I am always getting 
```
{
    errors =     (
                {
            code = 32;
            message = "Could not authenticate you.";
        }
    );
}
```
when making a signed request to https://api.twitter.com/1.1/users/show.json?screen_name=%@

this all worked fine before and the login process itself works fine

**Comment by nlutsenko** [comment] 2015-08-27 06:07
Hey @tzapu, thanks for the report. 
We've already seen a report on the SDK itself tracked in here ParsePlatform/Parse-SDK-iOS-OSX/issues/57

The workaround there should help you fix the issue, but it's going to be ultimately fixed once 1.8.2 is out. I'll close this issue to let you know when it's available.

**Comment by tzapu** [comment] 2015-08-27 06:11
wow, thanks, will try the workaround until the fix

**Comment by nlutsenko** [comment] 2015-08-28 00:52
Hey @tzapu, new version of Parse SDK (together with new version of ParseTwitterUtils) is available right now, which includes the fix for this issue.
Let me know if there is anything else I can help you with.

**Comment by tzapu** [comment] 2015-09-15 10:46
hi,
i still seem to be getting this error when trying to post a status update:

NSString *bodyString = [NSString stringWithFormat:@"status=%@", [textToShare stringByAddingPercentEncodingWithAllowedCharacters: [NSCharacterSet alphanumericCharacterSet]]];
                                                           // Explicitly percent-escape the '!' character.
                                                           bodyString = [bodyString stringByReplacingOccurrencesOfString:@"!" withString:@"%21"];
                                                           DLog(@"bodystring %@", bodyString);
                                                           NSURL *url = [NSURL URLWithString:@"https://api.twitter.com/1.1/statuses/update.json"];
                                                           NSMutableURLRequest *tweetRequest = [NSMutableURLRequest requestWithURL:url];
                                                           tweetRequest.HTTPMethod = @"POST";
                                                           tweetRequest.HTTPBody = [bodyString dataUsingEncoding:NSUTF8StringEncoding];
                                                           [[PFTwitterUtils twitter] signRequest:tweetRequest];
 [NSURLConnection sendAsynchronousRequest:tweetRequest queue:[NSOperationQueue mainQueue] completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
                                                          }];

any insight? Cheers

**Comment by nlutsenko** [comment] 2015-09-15 16:55
Will look into it, thanks.

**Comment by junya100** [comment] 2015-09-21 04:15
I have encountered same problem with iOS SDK version 1.8.5.

**Comment by phillfarrugia** [comment] 2015-09-21 12:12
I'm also having this issue, when comparing the PFTwitterUtils request with the CURL request using Twitter's API generator https://dev.twitter.com/oauth/tools/signature-generator/

It seemed the auth_consumer_key, oauth_nonce and auth_timestamp were all invalid.

**Comment by nlutsenko** [comment] 2015-09-21 23:48
Valid bug. Surfaces only on iOS 8.0+
Going to be fixed in Parse SDK 1.8.6

Current workaround - do not URLEncode (don't add percent escapes) to any item in queries/request body.

**Comment by nlutsenko** [comment] 2015-09-21 23:49
I am going to ping this issue when 1.8.6 is released.

**Comment by junya100** [comment] 2015-09-22 05:08
I got it. Thank you so much for your investigation.

**Comment by samyakjain** [comment] 2015-09-26 06:41
Can i do something before 1.8.6 is released ? Nothing seems to working .. Tweets are not getting posted? When is 1.8.6 is getting released?

**Comment by samyakjain** [comment] 2015-09-26 06:42
@tzapu @junya100 @phillfarrugia were you guys able to post tweet ?

**Comment by nlutsenko** [comment] 2015-09-26 06:43
I would suggest trying not to url-encode the tweet aka try posting without URL encoding it first.

**Comment by samyakjain** [comment] 2015-09-26 06:45
Getting 400 bad request .... seems like signRequest has some error?

**Comment by nlutsenko** [comment] 2015-09-26 06:46
The issue is fully fixed in the next SDK release, which is set for next week.
I am sorry, but it seems like we don't have a workaround until then.

**Comment by samyakjain** [comment] 2015-09-26 16:27
Something strange is happening , when user is logging in.. and in the call back if i try to post on twitter , it gets posted successfully but if i try to do same at later point of time, Tweet is not posted.

**Comment by tzapu** [comment] 2015-09-29 12:24
@samyakjain i was only able to post 1 word tweets. that it didn t have to encode. anything that involved any other character failed.

thanks @nlutsenko for keeping us in the loop

**Comment by samyakjain** [comment] 2015-09-29 12:29
@tzapu same thing is happening with me also. I can not release my app because of this.

**Comment by junya100** [comment] 2015-10-01 09:08
Hi @nlutsenko,

What day of next week about next SDK release?
We are waiting for that to submit our app to Apple.

**Comment by maxbryan** [comment] 2015-10-01 22:52
RT @junya100 @samyakjain @nlutsenko

**Comment by samyakjain** [comment] 2015-10-05 18:49
Any updates?

**Comment by junya100** [comment] 2015-10-09 01:01
@nlutsenko 1.9.0 released. Is this issue fixed with v1.9.0?

**Comment by nlutsenko** [comment] 2015-10-09 01:05
Yes it should be.
Let me guys know if the problem is fixed for you.

**Comment by junya100** [comment] 2015-10-09 01:20
I have confirmed it is fixed. Thanks!

**Comment by nlutsenko** [comment] 2015-10-09 02:14
Great, glad it helped you guys!

**Closed by nlutsenko** 2015-10-09 02:14 UTC
Labels: bug
