### ISSUE TITLE
When using login with Facebook w/ no system acct or app, safari launches incorrectly

### ISSUE THREAD

**Issue by henrytkirk** [ParsePlatform/ParseUI-iOS#158] opened 2015-09-20 18:36 UTC
Hi,

First - the FB login on the demo app crashes on iOS 9 SDK. I think this is because the plist needs some add'l settings. I'll try to get a pull request for it.

Second - when using iOS 9 SDK, and select Login with Facebook, and no system account is available nor is the native app installed, when it goes to launch Safari it presents it behind the login dialog and can't be interacted with. Prior to iOS 9, it would launch safari externally. Now it seems to launch it within the app behind the presented login dialog.

- Henry

**Comment by henrytkirk** [comment] 2015-09-20 18:38
Here's a screen shot:
![simulator screen shot sep 20 2015 11 37 32 am](https://cloud.githubusercontent.com/assets/387939/9982316/10c661b8-5f8c-11e5-87cb-5a9c7d9fcd69.png)

**Comment by henrytkirk** [comment] 2015-09-20 18:43
Adding this in my subclass fixes it, FYI:

[[PFFacebookUtils facebookLoginManager] setLoginBehavior:FBSDKLoginBehaviorSystemAccount];

**Comment by nlutsenko** [comment] 2015-09-21 05:37
Hey @henrytkirk, thanks for the report!

> First
Will double check, but it seems you are absolutely right. Fix is incoming in this case.

> Second
Will retest as well. Any chance your frontmost view controller is not LogInViewController whenever you are trying to authenticate with Facebook? The presentation of SafariViewController might be affected by view controller hierarchy.

The system account login behavior - I think it changed in the latest FBSDK (4.6), due to app link opening changes in iOS 9.

**Closed** 2015-09-23 20:59 UTC
Labels: needs investigation

**Comment by henrytkirk** [comment] 2015-09-23 21:08
Does this fix the safari issue w/ the Screen shot above?

**Comment by nlutsenko** [comment] 2015-09-23 21:11
No, shouldn't have. It just fixed the compilation and ability to run ParseUIDemo with Facebook Authenticaiton.
I've also tested ParseUIDemo for this issue (presentation behind the view controller) and can't seem to reproduce it with it's current state.

Any chance your frontmost view controller is not LogInViewController whenever you are trying to authenticate with Facebook? The presentation of SafariViewController might be affected by view controller hierarchy.

**Comment by henrytkirk** [comment] 2015-09-23 21:17
Oh good point. I am using presentViewController:animated:completion, and loginViewController should be frontmost, but I'll try presenting it from the root controller instead. Thx for idea.

**Comment by nlutsenko** [comment] 2015-09-23 21:17
(y)
